/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_registration_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Dilki
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainLogInJL = new javax.swing.JLabel();
        usernameJL = new javax.swing.JLabel();
        passwordJL = new javax.swing.JLabel();
        usernameJF = new javax.swing.JTextField();
        loginJB = new javax.swing.JButton();
        resetJB = new javax.swing.JButton();
        exitJB = new javax.swing.JButton();
        passwordJF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainLogInJL.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        MainLogInJL.setText("Log in");
        jPanel1.add(MainLogInJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 140, -1));

        usernameJL.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        usernameJL.setText("User Name");
        jPanel1.add(usernameJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        passwordJL.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        passwordJL.setText("Password");
        jPanel1.add(passwordJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        usernameJF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameJFMouseClicked(evt);
            }
        });
        usernameJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJFActionPerformed(evt);
            }
        });
        jPanel1.add(usernameJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 140, 30));

        loginJB.setBackground(new java.awt.Color(204, 204, 255));
        loginJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginJB.setText("Login");
        loginJB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJBActionPerformed(evt);
            }
        });
        jPanel1.add(loginJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 60, -1));

        resetJB.setBackground(new java.awt.Color(204, 204, 255));
        resetJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetJB.setText("Reset");
        resetJB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetJBActionPerformed(evt);
            }
        });
        jPanel1.add(resetJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 70, -1));

        exitJB.setBackground(new java.awt.Color(204, 204, 255));
        exitJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitJB.setText("Exit");
        exitJB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJBActionPerformed(evt);
            }
        });
        jPanel1.add(exitJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 60, -1));

        passwordJF.setText("uuuuuuuu");
        passwordJF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordJFMouseClicked(evt);
            }
        });
        passwordJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJFActionPerformed(evt);
            }
        });
        jPanel1.add(passwordJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJFActionPerformed

    private void loginJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJBActionPerformed
        String user=usernameJF.getText();
        String password=passwordJF.getText();
        if(password.equals("admin") && user.equals("applied")){

            MainWindow reg=new MainWindow();
            reg.setVisible(true);
            setVisible(false);
            dispose();
        }else if(!password.equals("admin") && user.equals("applied")){
            JOptionPane.showMessageDialog(null, " Incorrect Password..");
        }
        else if(password.equals("admin") && !user.equals("applied")){
            JOptionPane.showMessageDialog(null, " Incorrect User Name..");
        }
        else{
            JOptionPane.showMessageDialog(null, " Incorrect User Name & Password..");
        }
    }//GEN-LAST:event_loginJBActionPerformed

    private void resetJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetJBActionPerformed
        // TODO add your handling code here:
        usernameJF.setText(null);
        passwordJF.setText(null);
    }//GEN-LAST:event_resetJBActionPerformed

    private void exitJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJBActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitJBActionPerformed

    private void passwordJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJFActionPerformed

    private void usernameJFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameJFMouseClicked
        usernameJF.setText("");
    }//GEN-LAST:event_usernameJFMouseClicked

    private void passwordJFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordJFMouseClicked
        passwordJF.setText("");
    }//GEN-LAST:event_passwordJFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLogInJL;
    private javax.swing.JButton exitJB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginJB;
    private javax.swing.JPasswordField passwordJF;
    private javax.swing.JLabel passwordJL;
    private javax.swing.JButton resetJB;
    private javax.swing.JTextField usernameJF;
    private javax.swing.JLabel usernameJL;
    // End of variables declaration//GEN-END:variables
}
