/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_registration_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilki
 */
public class Registrations extends javax.swing.JFrame {
         Connection conn=new DbConnection().connect();
    /**
     * Creates new form Registrations
     */
    public Registrations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        nameJF = new javax.swing.JTextField();
        regnum = new javax.swing.JLabel();
        regNumJF = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        addressJF = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        emailJF = new javax.swing.JTextField();
        fac = new javax.swing.JComboBox();
        faculty = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        register = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Student Registration");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        fullname.setText("Full Name");
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 102, -1));
        jPanel2.add(nameJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        regnum.setText("Registration Number");
        jPanel2.add(regnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 116, -1));

        regNumJF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regNumJFFocusGained(evt);
            }
        });
        regNumJF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regNumJFMouseClicked(evt);
            }
        });
        jPanel2.add(regNumJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));

        address.setText("Address");
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, 61, -1));
        jPanel2.add(addressJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 153, 170, -1));

        gender.setText("Gender");
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        email.setText("Email");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        emailJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJFActionPerformed(evt);
            }
        });
        jPanel2.add(emailJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 209, 170, -1));

        fac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Applied Faculty", "Management Faculty", "Medical Faculty", "Tecnology Faculty", "Social sciences & Languages Faculty", "Geomatics Faculty", "Agricultural Faculty", " " }));
        fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facActionPerformed(evt);
            }
        });
        jPanel2.add(fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 170, -1));

        faculty.setText("Faculty");
        jPanel2.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 117, -1));

        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 65, -1));

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        register.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        male.setText("Male");
        male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleMouseClicked(evt);
            }
        });
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 182, -1, -1));

        female.setText("Female");
        female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleMouseClicked(evt);
            }
        });
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 182, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        gend="Female";
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        gend="Male";
    }//GEN-LAST:event_maleActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String RegNum=regNumJF.getText();
        String Fullname=nameJF.getText();
        String Address=addressJF.getText();
        String Email=emailJF.getText();

        if(Fullname.equals("")){
            JOptionPane.showMessageDialog(null, "Fill all details");

        }
        else if(RegNum.equals("")){
            JOptionPane.showMessageDialog(null, "Fill all details");
        }
        else if(Address.equals("")){
            JOptionPane.showMessageDialog(null, "Fill all details");
        }
        else if(Email.equals("")){
            JOptionPane.showMessageDialog(null, "Fill all details");
        }
        else if(!male.isSelected() && !female.isSelected()){
            JOptionPane.showMessageDialog(null, "Fill all details");
        }
        

        else{

            try{

                String sql ="INSERT INTO `student`( `Registration Number`, `Full Name` ,`Address`, `Gender`, `Email`, `Faculty` ) values(?,?,?,?,?,?)";
                PreparedStatement pst=conn.prepareStatement(sql);

                pst.setString(1,regNumJF.getText());
                pst.setString(2,nameJF.getText());
                pst.setString(3,addressJF.getText());

                if(male.isSelected()){

                    gend=male.getText();
                }
                if(female.isSelected()){

                    gend=female.getText();
                }

                pst.setString(4,gend);

                pst.setString(5,emailJF.getText());

                String faculty;
                faculty=fac.getSelectedItem().toString();
                pst.setString(6, faculty);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Added");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Registration Number Or Email already added...Try Again...");
            }

        }

    }//GEN-LAST:event_registerActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MainWindow reg=new MainWindow();
        reg.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

        regNumJF.setText("");
        nameJF.setText("");
        addressJF.setText("");
        male.setSelected(false);
        female.setSelected(false);
        emailJF.setText("");
        fac.setSelectedItem("Applied Faculty");
    }//GEN-LAST:event_clearActionPerformed

    private void facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facActionPerformed

    private void emailJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJFActionPerformed

    private void regNumJFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regNumJFFocusGained

    }//GEN-LAST:event_regNumJFFocusGained

    private void regNumJFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regNumJFMouseClicked
        regNumJF.setText("");
        nameJF.setText("");
        addressJF.setText("");
        male.setSelected(false);
        female.setSelected(false);
        emailJF.setText("");
        fac.setSelectedItem("Applied Faculty");
    }//GEN-LAST:event_regNumJFMouseClicked

    private void femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleMouseClicked
        male.setSelected(false);
    }//GEN-LAST:event_femaleMouseClicked

    private void maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleMouseClicked
        female.setSelected(false);
    }//GEN-LAST:event_maleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressJF;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailJF;
    private javax.swing.JComboBox fac;
    private javax.swing.JLabel faculty;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nameJF;
    private javax.swing.JTextField regNumJF;
    private javax.swing.JButton register;
    private javax.swing.JLabel regnum;
    // End of variables declaration//GEN-END:variables

        private String gend;
}
