/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_registration_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Dilki
 */
public class StudentDetails extends javax.swing.JFrame {
        Connection conn=new DbConnection().connect();
    /**
     * Creates new form StudentDetails
     */
    public StudentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stuDetais = new javax.swing.JLabel();
        regNum = new javax.swing.JLabel();
        regNumJF = new javax.swing.JTextField();
        fullName = new javax.swing.JLabel();
        nameJF = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        addressJF = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        genderJF = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailJF = new javax.swing.JTextField();
        backJB = new javax.swing.JButton();
        searchJB = new javax.swing.JButton();
        faculty = new javax.swing.JLabel();
        facultyJF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stuDetais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stuDetais.setText("Student Details");
        jPanel1.add(stuDetais, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 168, -1));

        regNum.setText("Registration  Number");
        jPanel1.add(regNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 48, -1, -1));

        regNumJF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regNumJFMouseClicked(evt);
            }
        });
        regNumJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNumJFActionPerformed(evt);
            }
        });
        regNumJF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regNumJFKeyPressed(evt);
            }
        });
        jPanel1.add(regNumJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 240, -1));

        fullName.setText("Full Name");
        jPanel1.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        nameJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJFActionPerformed(evt);
            }
        });
        jPanel1.add(nameJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 240, -1));

        address.setText("Address");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel1.add(addressJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 240, -1));

        gender.setText("Gender");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        genderJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderJFActionPerformed(evt);
            }
        });
        jPanel1.add(genderJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 240, -1));

        email.setText("E-mail");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        emailJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJFActionPerformed(evt);
            }
        });
        jPanel1.add(emailJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, -1));

        backJB.setText("BACK");
        backJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBActionPerformed(evt);
            }
        });
        jPanel1.add(backJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        searchJB.setText("Search");
        searchJB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchJBMouseClicked(evt);
            }
        });
        searchJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJBActionPerformed(evt);
            }
        });
        jPanel1.add(searchJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        faculty.setText("Faculty");
        jPanel1.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel1.add(facultyJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regNumJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNumJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNumJFActionPerformed

    private void nameJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJFActionPerformed

    private void genderJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderJFActionPerformed

    private void emailJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJFActionPerformed

    private void backJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBActionPerformed
        // TODO add your handling code here:
        MainWindow reg=new MainWindow();
        reg.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backJBActionPerformed

    private void searchJBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchJBMouseClicked

    }//GEN-LAST:event_searchJBMouseClicked

    private void searchJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJBActionPerformed
        
        String tmp=(String)regNumJF.getText();
        String sql ="SELECT `Full Name`, `Address`, `Gender`, `Email`, `Faculty` FROM `student` WHERE `Registration Number` LIKE ?";
        try{
            PreparedStatement statment =conn.prepareStatement(sql);
            statment.setString(1,tmp);
            ResultSet rs=statment.executeQuery();

            if(rs.next()){
                String add1=rs.getString("Full Name");
                nameJF.setText(add1);

                String add2=rs.getString("Address");
                addressJF.setText(add2);

                String add3=rs.getString("Gender");
                genderJF.setText(add3);

                String add4=rs.getString("Email");
                emailJF.setText(add4);

                String add5=rs.getString("Faculty");
                facultyJF.setText(add5);
                
                
            }
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_searchJBActionPerformed

    private void regNumJFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regNumJFKeyPressed
        
        
        
    }//GEN-LAST:event_regNumJFKeyPressed

    private void regNumJFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regNumJFMouseClicked
        regNumJF.setText("");
        nameJF.setText("");
        addressJF.setText("");
        genderJF.setText("");
        emailJF.setText("");
        facultyJF.setText("");
    }//GEN-LAST:event_regNumJFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressJF;
    private javax.swing.JButton backJB;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailJF;
    private javax.swing.JLabel faculty;
    private javax.swing.JTextField facultyJF;
    private javax.swing.JLabel fullName;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField genderJF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameJF;
    private javax.swing.JLabel regNum;
    private javax.swing.JTextField regNumJF;
    private javax.swing.JButton searchJB;
    private javax.swing.JLabel stuDetais;
    // End of variables declaration//GEN-END:variables
}
